# JQueryHelperBundle Configuration

enable:             true

jquery:
  version:          1.7.2
  ssl:              false
  localpath:        false

jqueryui:
  version:          1.8.11
  ssl:              false
  localpath:        false

noconflictmode:
  enable:                false
  noConflictModeHandler: '$j'