# JQueryHelperBundle Configuration

enable:             		false

jquery:
    version:          		1.7.2
    ssl:              		false
    localpath:        		false

jqueryui:
    version:          		1.8.21
    ssl:              		false
    localpath:        		false

noconflictmode:
    enable:                	false
    noConflictModeHandler: 	'$j'
